export const finalStandingsEuro2024 = [
  { country: "Spain", result: "champion" },
  { country: "England", result: "runner-up" },
  { country: "France", result: "semifinals" },
  { country: "Netherlands", result: "semifinals" },
  { country: "Germany", result: "quarterfinals" },
  { country: "Portugal", result: "quarterfinals" },
  { country: "Switzerland", result: "quarterfinals" },
  { country: "Turkey", result: "quarterfinals" },
  { country: "Italy", result: "knockout-stage" },
  { country: "Belgium", result: "knockout-stage" },
  { country: "Austria", result: "knockout-stage" },
  { country: "Romania", result: "knockout-stage" },
  { country: "Slovakia", result: "knockout-stage" },
  { country: "Slovenia", result: "knockout-stage" },
  { country: "Denmark", result: "knockout-stage" },
  { country: "Georgia", result: "knockout-stage" },
  { country: "Croatia", result: "group-stage" },
  { country: "CzechRepublic", result: "group-stage" },
  { country: "Hungary", result: "group-stage" },
  { country: "Serbia", result: "group-stage" },
  { country: "Poland", result: "group-stage" },
  { country: "Scotland", result: "group-stage" },
  { country: "Albania", result: "group-stage" },
  { country: "Ukraine", result: "group-stage" },
  { country: "Russia", result: "DSQ" },
  { country: "Belarus", result: "DSQ" },
];
