export const finalStandingsEurobasket2022 = [
  { country: "Spain", result: "champion" },
  { country: "France", result: "runner-up" },
  { country: "Germany", result: "bronze" },
  { country: "Poland", result: "semifinals" },
  { country: "Greece", result: "quarterfinals" },
  { country: "Slovenia", result: "quarterfinals" },
  { country: "Italy", result: "quarterfinals" },
  { country: "Finland", result: "quarterfinals" },
  { country: "Serbia", result: "knockout-stage" },
  { country: "Ukraine", result: "knockout-stage" },
  { country: "Croatia", result: "knockout-stage" },
  { country: "Montenegro", result: "knockout-stage" },
  { country: "Belgium", result: "knockout-stage" },
  { country: "Lithuania", result: "knockout-stage" },
  { country: "CzechRepublic", result: "knockout-stage" },
  { country: "BosniaandHerzegovina", result: "group-stage" },
  { country: "Estonia", result: "group-stage" },
  { country: "Bulgaria", result: "group-stage" },
  { country: "Netherlands", result: "group-stage" },
  { country: "Hungary", result: "group-stage" },
  { country: "UnitedKingdom", result: "group-stage" },
  { country: "Russia", result: "DSQ" },
  { country: "Belarus", result: "DSQ" },
];
