/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CarsRouteRouteImport } from './routes/cars/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as CarsIdRouteImport } from './routes/cars/$id'
import { Route as ApiCarsIndexRouteImport } from './routes/api/cars/index'
import { Route as ApiCarsIdRouteImport } from './routes/api/cars/$id'

const CarsRouteRoute = CarsRouteRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarsRouteRoute,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarsRouteRoute,
} as any)
const ApiCarsIndexRoute = ApiCarsIndexRouteImport.update({
  id: '/api/cars/',
  path: '/api/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarsIdRoute = ApiCarsIdRouteImport.update({
  id: '/api/cars/$id',
  path: '/api/cars/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteRouteWithChildren
  '/cars/$id': typeof CarsIdRoute
  '/cars/': typeof CarsIndexRoute
  '/api/cars/$id': typeof ApiCarsIdRoute
  '/api/cars': typeof ApiCarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars/$id': typeof CarsIdRoute
  '/cars': typeof CarsIndexRoute
  '/api/cars/$id': typeof ApiCarsIdRoute
  '/api/cars': typeof ApiCarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteRouteWithChildren
  '/cars/$id': typeof CarsIdRoute
  '/cars/': typeof CarsIndexRoute
  '/api/cars/$id': typeof ApiCarsIdRoute
  '/api/cars/': typeof ApiCarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/cars/$id'
    | '/cars/'
    | '/api/cars/$id'
    | '/api/cars'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cars/$id' | '/cars' | '/api/cars/$id' | '/api/cars'
  id:
    | '__root__'
    | '/'
    | '/cars'
    | '/cars/$id'
    | '/cars/'
    | '/api/cars/$id'
    | '/api/cars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsRouteRoute: typeof CarsRouteRouteWithChildren
  ApiCarsIdRoute: typeof ApiCarsIdRoute
  ApiCarsIndexRoute: typeof ApiCarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof CarsRouteRoute
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof CarsRouteRoute
    }
    '/api/cars/': {
      id: '/api/cars/'
      path: '/api/cars'
      fullPath: '/api/cars'
      preLoaderRoute: typeof ApiCarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cars/$id': {
      id: '/api/cars/$id'
      path: '/api/cars/$id'
      fullPath: '/api/cars/$id'
      preLoaderRoute: typeof ApiCarsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CarsRouteRouteChildren {
  CarsIdRoute: typeof CarsIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

const CarsRouteRouteChildren: CarsRouteRouteChildren = {
  CarsIdRoute: CarsIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}

const CarsRouteRouteWithChildren = CarsRouteRoute._addFileChildren(
  CarsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsRouteRoute: CarsRouteRouteWithChildren,
  ApiCarsIdRoute: ApiCarsIdRoute,
  ApiCarsIndexRoute: ApiCarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
