export const coronaVirusAffectedByCountry = [
  { country: "Italy", affected: 4636 },
  { country: "Germany", affected: 687 },
  { country: "France", affected: 613 },
  { country: "Spain", affected: 443 },
  { country: "Switzerland", affected: 210 },
  { country: "England", affected: 163 },
  { country: "Sweden", affected: 137 },
  { country: "Netherdlands", affected: 128 },
  { country: "Norway", affected: 113 },
  { country: "Austria", affected: 55 },
  { country: "Greece", affected: 46 },
  { country: "Iceland", affected: 45 },
  { country: "San Marino", affected: 23 },
  { country: "Denmark", affected: 23 },
  { country: "Ireland", affected: 18 },
  { country: "Czech Republic", affected: 18 },
  { country: "Finland", affected: 15 },
  { country: "Croatia", affected: 11 },
  { country: "Estonia", affected: 10 },
  { country: "Portugal", affected: 8 },
  { country: "Russia", affected: 8 },
  { country: "Romania", affected: 6 },
  { country: "Poland", affected: 5 },
  { country: "Luxembourg", affected: 3 },
  { country: "Hungary", affected: 3 },
  { country: "Macedonia", affected: 1 },
  { country: "Lithuania", affected: 1 },
  { country: "Monaco", affected: 1 },
];
