name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{ github.repository_owner }}"
          package-manager-cache: false

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Version or publish packages
        uses: changesets/action@v2
        with:
          publish-script: npm run publish-packages
        env:
          # See https://github.com/changesets/action/issues/132
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
